apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground
  namespace: dev
  labels:
    app: wil42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
        - name: playground
          image: "yeasy/simple-web"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wil42-playground-service
  namespace: dev
spec:
  selector:
    app: wil42-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
  type: LoadBalancer